version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: solinftec
      POSTGRES_DB: stockbanc
    volumes:
      - /var/lib/postgresql/data
    restart: always
  # api:
  #   image: "joaocobo20/tradeactions:api-users"
  #   ports:
  #     - 8083:8083
  #   environment:
  #     DB_URL: jdbc:postgresql://database:5432/postgres
  #   restart: always
  # apistocks:
  #   image: "joaocobo20/tradeactions:api-stocks"
  #   ports:
  #     - 8084:8084
  #   environment:
  #     DB_URL: jdbc:postgresql://database:5432/stockbanc
  #   restart: always
  # front:
  #   image: "joaocobo20/tradeactions:front"
  #   ports:
  #     - 8080:80
  # websocket:
  #   image: "joaocobo20/tradeactions:websocket"
  #   ports:
  #     - 8085:8085
